# Site
repository: RongLiu-Leo/rongliu-leo.github.io
favicon: images/USC.png

# Content configuration version
version: 2

# Personal info
name: Rong Liu
title: Research Engineer
affiliation: USC Institute for Creative Technologies
email: roliu@ict.usc.edu
website: https://rongliu-leo.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  RongLiu-Leo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: rong-liu-34a3b4251
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
googlescholar_username: MrWUyWkAAAAJ





# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I’m Rong Liu, a Research Engineer at the USC Institute for Creative Technologies.
  
  My research focuses on how we **understand**, **reconstruct**, and **generate** our everyday **interactive** and **dynamic world** through computer vision, graphics, and machine learning.


content:

  - title: Publications
    layout: image
    content:
      - title: 'Universal Beta Splatting'
        image: images/ubs.png
        links: |
          [Website](https://rongliu-leo.github.io/universal-beta-splatting/) | 
          [Paper](https://arxiv.org/abs/2510.03312) | 
          [Code](https://github.com/RongLiu-Leo/universal-beta-splatting)
        description: |
          **Rong Liu**, Zhongpai Gao, Benjamin Planche, Meida Chen, Van Nguyen Nguyen, Meng Zheng, Anwesa Choudhuri, Terrence Chen, Yue Wang, Andrew Feng, Ziyan Wu

          Pre-Print arXiv:2510.03312

          *Universal Beta Splatting generalizes 3D Gaussian Splatting to N-dimensional anisotropic Beta kernels, enabling controllable dependency modeling across spatial, angular, and temporal dimensions within a single representation.*

      - title: 'Splat Feature Solver'
        video: videos/splat_feature_solver.mp4
        links: |
          [Website](https://splat-distiller.pages.dev/) | 
          [Paper](https://arxiv.org/abs/2508.12216) | 
          [Code](https://github.com/saliteta/splat-distiller/)
        description: |
          Butian Xiong, **Rong Liu**, Kenneth Xu, Meida Chen, Andrew Feng

          Pre-Print arXiv:2508.12216

          *A unified, kernel- and feature-agnostic framework that formulates feature lifting as a sparse linear inverse problem, enabling efficient closed-form solutions with high-quality 3D semantic features.*

      - title: 'Deformable Beta Splatting'
        video: videos/dbs.mp4
        links: |
          [Website](https://rongliu-leo.github.io/beta-splatting/) | 
          [Paper](https://arxiv.org/abs/2501.18630) | 
          [Code](https://github.com/RongLiu-Leo/beta-splatting/)
        description: |
          **Rong Liu\***, Dylan Sun\*, Meida Chen, Yue Wang†, Andrew Feng†

          2025 ACM Special Interest Group on Computer Graphics and Interactive Techniques (**SIGGRAPH 2025**)

          *Deformable Beta Splatting introduces deformable Beta Kernels with adaptive frequency control for both geometry and color encoding, capturing complex geometries and lighting while only using 45% parameters and rendering 1.5x faster than 3DGS-MCMC.*

      - title: 'SplatMAP: Online Dense Monocular SLAM with 3D Gaussian Splatting'
        video: videos/splatmap.mp4
        links: |
          [Paper](https://arxiv.org/abs/2501.07015) 
        description: |
          Yue Hu, **Rong Liu**, Meida Chen, Peter Beerel, Andrew Feng

          2025 ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games (**I3D 2025**)

          *A real-time monocular SLAM system that fuses 3D Gaussian Splatting with SLAM’s dynamic depth and pose updates via SLAM-Informed Adaptive Densification and Geometry-Guided Optimization.*

      - title: 'AtomGS: Atomizing Gaussian Splatting for High-Fidelity Radiance Field'
        video: videos/atomgs.mp4
        links: |
          [Website](https://rongliu-leo.github.io/AtomGS/) | 
          [Paper](https://arxiv.org/abs/2405.12369) | 
          [Code](https://github.com/RongLiu-Leo/AtomGS) | 
          [Poster](https://bmva-archive.org.uk/bmvc/2024/papers/Paper_577/poster.pdf)
        description: |
          **Rong Liu**, Rui Xu, Yue Hu, Meida Chen, Andrew Feng

          35th British Machine Vision Conference 2024 (**BMVC 2024**)

          *AtomGS proposes an atomized proliferation of Gaussians and edge-aware normal loss to refine Gaussian splatting, boosting geometric precision and rendering fidelity in novel-view synthesis.*

      - title: 'UAV swarm based radar signal sorting via multi-source data fusion: A deep transfer learning framework'
        image: images/UAV.jpg
        links: |
          [Paper](https://www.sciencedirect.com/science/article/pii/S1566253521001834) | 
          [Patent](https://patentscope.wipo.int/search/en/detail.jsf?docPN=CN113030958)
        description: |
          Liangtian Wan, **Rong Liu**, Lu Sun, Hansong Nie, Xianpeng Wang

          **Information Fusion**. 78 (2022): 90-101

          *A UAV-swarm–enabled deep transfer learning framework that fuses radar pulses across time and space to accurately classify and sort complex radar signals.*

  - title: Projects
    layout: image
    content:
      - title: 'Gaussian Splatting Monitor'
        video: videos/GSS.mp4
        links: |
          [Website](https://rongliu-leo.github.io/Gaussian-Splatting-Monitor/) | 
          [Code](https://github.com/RongLiu-Leo/Gaussian-Splatting-Monitor)
        description: | # this will include new lines to allow paragraphs
          **Rong Liu**, Shuyang Zhang, Ning Nie

          *A real-time tool that provides additional differentiable outputs for visualizing and diagnosing 3D Gaussian Splatting pipelines.*
      
      - title: 'Universal Photorealistic Style Transfer: A Lightweight and Adaptive Approach'
        video: videos/IPST.mp4
        links: |
          [Website](https://rongliu-leo.github.io/IPST/) | 
          [Paper](https://arxiv.org/abs/2309.10011) | 
          [Code](https://github.com/RongLiu-Leo/Video-Style-Transfer)
        description: |
          **Rong Liu**, Enyu Zhao, Zhiyuan Liu, Andrew Feng, Scott John Easley

          Pre-Print arXiv:2309.10011

          *A lightweight style transfer network that learns instance-adaptive photorealistic transfer on-the-fly and scales effortlessly to high-resolution images and videos.*

  - title: Experiences
    layout: list
    content: 
      - title: Research Engineer
        sub_title: USC Institute for Creative Technologies
        supervisor: "Supervisor: Prof. Andrew Feng"
        caption: May 2024 - Present
        layout: left
        description: |
          - Deformable Beta Splatting
          - SplatMAP: Online Dense Monocular SLAM with 3D Gaussian Splatting
          - Splat Feature Solver

      - title: Research Intern
        sub_title: United Imaging Intelligence
        supervisor: "Supervisor: Dr. Zhongpai Gao"
        caption: June 2025 - September 2025
        layout: left
        description: |
          - Universal Beta Splatting
          - Radiance fields on medical data

      - title: Research Assistant
        sub_title: USC Institute for Creative Technologies
        supervisor: "Supervisor: Prof. Andrew Feng"
        caption: May 2023 - May 2024
        layout: left
        description: |
          - Neural Radiance Fields (NeRF)
          - Scalable NeRF on large terrain datasets
          - 3D Gaussian Splatting
          - Atomizing Gaussian Splatting for High-Fidelity Radiance Field
          - Mesh extraction from Radiance Field
          
      - title: Research Assistant
        sub_title: Dalian University of Technology
        supervisor: "Supervisor: Prof. Liangtian Wan"
        caption: July 2020 - July 2022
        layout: left
        description: |
          - Objective Detection (RCNN and YOLO)
          - Transfer Learning
     
      - title: Teaching Assistant
        sub_title: Dalian University of Technology
        caption: September 2021 - June 2022
        layout: left
        description: |
          - Program Design Basics and C Programming
          - Object-Oriented Method and C++ Program Design
               
  - title: Awards
    layout: text
    content: |

      - **[Computer Science Master's Student Honors Merit](./images/Honor.pdf)** - University of Southern California (USC), 2024

      - **DUT Outstanding Undergraduate Thesis** - Dalian University of Technology (DUT), 2022

      - **First Prize in the National Artificial Intelligence Knowledge Competition for College Students** - JiangSu Association of Artificial Intelligence (JSAI), 2020

      - **Meritorious Winner in Mathematical Contest in Modeling** - Consortium for Mathematics and Its Applications (COMAP), 2019 

  - title: Service
    layout: text
    content: |

      - **Program Committee:** [Advanced Perception for Autonomous Healthcare](https://apahws.github.io/) @ ICCV 2025

      - **Workshop Reviewer:** [APAH](https://apahws.github.io/) @ ICCV 2025

      - **Journal Reviewer:** [TCSVT](https://dl.acm.org/journal/ieeetcsvt), [TOMM](https://dl.acm.org/journal/tomm), [TIP](https://dl.acm.org/journal/tip), [TOM](https://dl.acm.org/journal/tom)

      


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
